import 'package:pest_lens_app/models/account_status_enum.dart';
import 'package:pest_lens_app/models/role_enum.dart';
import 'package:pest_lens_app/models/user_full_info_model.dart';

// Dummy data for UI testing
final List<UserFullInfoModel> dummyUsers = [
  UserFullInfoModel(
    id: 'user_0',
    username: 'username_0',
    email: 'user0@example.com',
    firstName: 'FirstName0',
    lastName: 'LastName0',
    phoneNumber: '0987678987',
    avatarUrl:
        'https://images.pexels.com/photos/45201/kitty-cat-kitten-pet-45201.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500',
    createdAt: DateTime.now().subtract(Duration(days: 0)),
    lastLogin: DateTime.now().subtract(Duration(days: 0)),
    roles: Role.ROLE_ADMIN,
    status: AccountStatusEnum.ACTIVE,
  ),
  UserFullInfoModel(
    id: 'user_1',
    username: 'username_1',
    email: 'user1@example.com',
    firstName: 'FirstName1',
    lastName: 'LastName1',
    phoneNumber: '0987678987',
    avatarUrl:
        'https://images.pexels.com/photos/45201/kitty-cat-kitten-pet-45201.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500',
    createdAt: DateTime.now().subtract(Duration(days: 30)),
    lastLogin: null,
    roles: Role.ROLE_USER,
    status: AccountStatusEnum.INACTIVE,
  ),
  UserFullInfoModel(
    id: 'user_2',
    username: 'username_2',
    email: 'user2@example.com',
    firstName: 'FirstName2',
    lastName: 'LastName2',
    phoneNumber: '0987678987',
    avatarUrl:
        'https://images.pexels.com/photos/45201/kitty-cat-kitten-pet-45201.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500',
    createdAt: DateTime.now().subtract(Duration(days: 60)),
    lastLogin: DateTime.now().subtract(Duration(days: 2)),
    roles: Role.ROLE_ADMIN,
    status: AccountStatusEnum.DEACTIVATED,
  ),
  UserFullInfoModel(
    id: 'user_3',
    username: 'username_3',
    email: 'user3@example.com',
    firstName: 'FirstName3',
    lastName: 'LastName3',
    phoneNumber: '0987678987',
    avatarUrl:
        'https://images.pexels.com/photos/45201/kitty-cat-kitten-pet-45201.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500',
    createdAt: DateTime.now().subtract(Duration(days: 90)),
    lastLogin: null,
    roles: Role.ROLE_USER,
    status: AccountStatusEnum.PENDING,
  ),
  UserFullInfoModel(
    id: 'user_4',
    username: 'username_4',
    email: 'user4@example.com',
    firstName: 'FirstName4',
    lastName: 'LastName4',
    phoneNumber: '0987678987',
    avatarUrl:
        'https://images.pexels.com/photos/45201/kitty-cat-kitten-pet-45201.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500',
    createdAt: DateTime.now().subtract(Duration(days: 120)),
    lastLogin: DateTime.now().subtract(Duration(days: 4)),
    roles: Role.ROLE_ADMIN,
    status: AccountStatusEnum.ACTIVE,
  ),
  UserFullInfoModel(
    id: 'user_5',
    username: 'username_5',
    email: 'user5@example.com',
    firstName: 'FirstName5',
    lastName: 'LastName5',
    phoneNumber: '0987678987',
    avatarUrl:
        'https://images.pexels.com/photos/45201/kitty-cat-kitten-pet-45201.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500',
    createdAt: DateTime.now().subtract(Duration(days: 150)),
    lastLogin: null,
    roles: Role.ROLE_USER,
    status: AccountStatusEnum.INACTIVE,
  ),
  UserFullInfoModel(
    id: 'user_6',
    username: 'username_6',
    email: 'user6@example.com',
    firstName: 'FirstName6',
    lastName: 'LastName6',
    phoneNumber: '0987678987',
    avatarUrl:
        'https://images.pexels.com/photos/45201/kitty-cat-kitten-pet-45201.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500',
    createdAt: DateTime.now().subtract(Duration(days: 180)),
    lastLogin: DateTime.now().subtract(Duration(days: 6)),
    roles: Role.ROLE_ADMIN,
    status: AccountStatusEnum.DEACTIVATED,
  ),
  UserFullInfoModel(
    id: 'user_7',
    username: 'username_7',
    email: 'user7@example.com',
    firstName: 'FirstName7',
    lastName: 'LastName7',
    phoneNumber: '0987678987',
    avatarUrl:
        'https://images.pexels.com/photos/45201/kitty-cat-kitten-pet-45201.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500',
    createdAt: DateTime.now().subtract(Duration(days: 210)),
    lastLogin: null,
    roles: Role.ROLE_USER,
    status: AccountStatusEnum.PENDING,
  ),
  UserFullInfoModel(
    id: 'user_8',
    username: 'username_8',
    email: 'user8@example.com',
    firstName: 'FirstName8',
    lastName: 'LastName8',
    phoneNumber: '0987678987',
    avatarUrl:
        'https://images.pexels.com/photos/45201/kitty-cat-kitten-pet-45201.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500',
    createdAt: DateTime.now().subtract(Duration(days: 240)),
    lastLogin: DateTime.now().subtract(Duration(days: 8)),
    roles: Role.ROLE_ADMIN,
    status: AccountStatusEnum.ACTIVE,
  ),
  UserFullInfoModel(
    id: 'user_9',
    username: 'username_9',
    email: 'user9@example.com',
    firstName: 'FirstName9',
    lastName: 'LastName9',
    phoneNumber: '0987678987',
    avatarUrl:
        'https://images.pexels.com/photos/45201/kitty-cat-kitten-pet-45201.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500',
    createdAt: DateTime.now().subtract(Duration(days: 270)),
    lastLogin: null,
    roles: Role.ROLE_USER,
    status: AccountStatusEnum.INACTIVE,
  ),
  UserFullInfoModel(
    id: 'user_10',
    username: 'username_10',
    email: 'user10@example.com',
    firstName: 'FirstName10',
    lastName: 'LastName10',
    phoneNumber: '0987678987',
    avatarUrl:
        'https://images.pexels.com/photos/45201/kitty-cat-kitten-pet-45201.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500',
    createdAt: DateTime.now().subtract(Duration(days: 300)),
    lastLogin: DateTime.now().subtract(Duration(days: 10)),
    roles: Role.ROLE_ADMIN,
    status: AccountStatusEnum.DEACTIVATED,
  ),
  UserFullInfoModel(
    id: 'user_11',
    username: 'username_11',
    email: 'user11@example.com',
    firstName: 'FirstName11',
    lastName: 'LastName11',
    phoneNumber: '0987678987',
    avatarUrl:
        'https://images.pexels.com/photos/45201/kitty-cat-kitten-pet-45201.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500',
    createdAt: DateTime.now().subtract(Duration(days: 330)),
    lastLogin: null,
    roles: Role.ROLE_USER,
    status: AccountStatusEnum.PENDING,
  ),
  UserFullInfoModel(
    id: 'user_12',
    username: 'username_12',
    email: 'user12@example.com',
    firstName: 'FirstName12',
    lastName: 'LastName12',
    phoneNumber: '0987678987',
    avatarUrl:
        'https://images.pexels.com/photos/45201/kitty-cat-kitten-pet-45201.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500',
    createdAt: DateTime.now().subtract(Duration(days: 360)),
    lastLogin: DateTime.now().subtract(Duration(days: 12)),
    roles: Role.ROLE_ADMIN,
    status: AccountStatusEnum.ACTIVE,
  ),
  UserFullInfoModel(
    id: 'user_13',
    username: 'username_13',
    email: 'user13@example.com',
    firstName: 'FirstName13',
    lastName: 'LastName13',
    phoneNumber: '0987678987',
    avatarUrl:
        'https://images.pexels.com/photos/45201/kitty-cat-kitten-pet-45201.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500',
    createdAt: DateTime.now().subtract(Duration(days: 390)),
    lastLogin: null,
    roles: Role.ROLE_USER,
    status: AccountStatusEnum.INACTIVE,
  ),
  UserFullInfoModel(
    id: 'user_14',
    username: 'username_14',
    email: 'user14@example.com',
    firstName: 'FirstName14',
    lastName: 'LastName14',
    phoneNumber: '0987678987',
    avatarUrl:
        'https://images.pexels.com/photos/45201/kitty-cat-kitten-pet-45201.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500',
    createdAt: DateTime.now().subtract(Duration(days: 420)),
    lastLogin: DateTime.now().subtract(Duration(days: 14)),
    roles: Role.ROLE_ADMIN,
    status: AccountStatusEnum.DEACTIVATED,
  ),
  UserFullInfoModel(
    id: 'user_15',
    username: 'username_15',
    email: 'user15@example.com',
    firstName: 'FirstName15',
    lastName: 'LastName15',
    phoneNumber: '0987678987',
    avatarUrl:
        'https://images.pexels.com/photos/45201/kitty-cat-kitten-pet-45201.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500',
    createdAt: DateTime.now().subtract(Duration(days: 450)),
    lastLogin: null,
    roles: Role.ROLE_USER,
    status: AccountStatusEnum.PENDING,
  ),
  UserFullInfoModel(
    id: 'user_16',
    username: 'username_16',
    email: 'user16@example.com',
    firstName: 'FirstName16',
    lastName: 'LastName16',
    phoneNumber: '0987678987',
    avatarUrl:
        'https://images.pexels.com/photos/45201/kitty-cat-kitten-pet-45201.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500',
    createdAt: DateTime.now().subtract(Duration(days: 480)),
    lastLogin: DateTime.now().subtract(Duration(days: 16)),
    roles: Role.ROLE_ADMIN,
    status: AccountStatusEnum.ACTIVE,
  ),
  UserFullInfoModel(
    id: 'user_17',
    username: 'username_17',
    email: 'user17@example.com',
    firstName: 'FirstName17',
    lastName: 'LastName17',
    phoneNumber: '0987678987',
    avatarUrl:
        'https://images.pexels.com/photos/45201/kitty-cat-kitten-pet-45201.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500',
    createdAt: DateTime.now().subtract(Duration(days: 510)),
    lastLogin: null,
    roles: Role.ROLE_USER,
    status: AccountStatusEnum.INACTIVE,
  ),
  UserFullInfoModel(
    id: 'user_18',
    username: 'username_18',
    email: 'user18@example.com',
    firstName: 'FirstName18',
    lastName: 'LastName18',
    phoneNumber: '0987678987',
    avatarUrl:
        'https://images.pexels.com/photos/45201/kitty-cat-kitten-pet-45201.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500',
    createdAt: DateTime.now().subtract(Duration(days: 540)),
    lastLogin: DateTime.now().subtract(Duration(days: 18)),
    roles: Role.ROLE_ADMIN,
    status: AccountStatusEnum.DEACTIVATED,
  ),
  UserFullInfoModel(
    id: 'user_19',
    username: 'username_19',
    email: 'user19@example.com',
    firstName: 'FirstName19',
    lastName: 'LastName19',
    phoneNumber: '0987678987',
    avatarUrl:
        'https://images.pexels.com/photos/45201/kitty-cat-kitten-pet-45201.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500',
    createdAt: DateTime.now().subtract(Duration(days: 570)),
    lastLogin: null,
    roles: Role.ROLE_USER,
    status: AccountStatusEnum.PENDING,
  ),
];
