// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAxivaEYbYf_P4OWtDzq2ir12uNa9GonHg',
    appId: '1:761576439452:android:7a8b03a55008165bdbb759',
    messagingSenderId: '761576439452',
    projectId: 'pestapp-201a5',
    storageBucket: 'pestapp-201a5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCbIy7sLg2DrMcyeDlHlUYQX9YBRtkuPZ0',
    appId: '1:761576439452:ios:2dfeb7ee2bbeb61cdbb759',
    messagingSenderId: '761576439452',
    projectId: 'pestapp-201a5',
    storageBucket: 'pestapp-201a5.appspot.com',
    iosBundleId: 'com.example.pestLensApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCbIy7sLg2DrMcyeDlHlUYQX9YBRtkuPZ0',
    appId: '1:761576439452:ios:2dfeb7ee2bbeb61cdbb759',
    messagingSenderId: '761576439452',
    projectId: 'pestapp-201a5',
    storageBucket: 'pestapp-201a5.appspot.com',
    iosBundleId: 'com.example.pestLensApp',
  );
}
